next.config.js
pages/[voteid].js

- wallets retained by DeWi
- Light metadata for these two votes. Edit freely.
- Block times may need adjustment depending on merge time.

Roughs out 2 48hr votes

---

pages/index.js

I made some small tweaks to main index page for when there are 3 votecards.

Responsive tweaks

---

jobs/calculate-results.js
yarn.lock

May help with our overhead. The roles endpoint is more performant than the activity one even though this creates a bit of an N+1 query

Updates to calculation job

---

next.config.js

HIP 54 & HIP 55

---

next.config.js
pages/[voteid].js

Sets up HIP 56 for a 5-day vote; terminating on block 1256800 (approx Sunday morning PST)
---
note to @danielcolinjames: 0c9a4da61df7b0bb6c36eb730fa6824fa862be37

HIP 56 - Improved State Channel Disputes

---

next.config.js

HIP51 Vote

---

next.config.js

-HIP 73 vote launch
-Text reviewed by Foundation
-Vote to close on Oct 23rd.

launching hip 73

---

jobs/db-calculate-results.js

so that the page doesn't crash on load.

Provides structure for default cache

---

next.config.js

exactly 7 days with a little extra time for deployment

update block time to exactly 7 days

---

next.config.js

Had an error to check file [voteid] on my local server - @abhay 
and something about URLs is not supported. Got it showing on the local server once but no time after that. Don't know enough to tell what's wrong.

add hip 76 to helium.vote

---

next.config.js

Updates 76 to be both Technical & Economic

HIP 76 Category

---

next.config.js

PR to get HIP 77 vote live!
@jthiller and @abhay for review

get hip 77 vote live

---

next.config.js

update addresses and blocktimes

relaunch hip 77

---

components/VoteBreakdown.tsx
components/VoteOption.tsx
components/VoteResults.tsx
hooks/useVotes.ts
pages/[proposalKey].tsx

Add voter breakdown

---

components/LockTokensModal.tsx
components/VoteBreakdown.tsx
components/VotingPowerBox.tsx
pages/[network]/proposals/[proposalKey].tsx

Replace text instances of weight with power

---

mobile-proposals.json

Fix working group elections link

---

src/components/Proposal.tsx
src/components/VoteResults.tsx

Not sure how I feel about this yet. Will gather some feedback from the community.

Show result after voting

---

tsconfig.json

OH: "Is it really js if you don't feel unclean after using it?"

add ts-node compiler options

---

package.json
src/providers/WalletProvider.tsx
yarn.lock

also upgrades solflare adapter

Adds coinbase wallet adapter

---

mobile-proposals.json

Need a second entry since the other one is already out there (even though it's not approved yet).

Add HIP 139 Again

---

helium-proposals.json

Adding this ahead of tomorrow's community call.

Add May proposals
